import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/dist/server/api-utils";
import TRPCProvider from "./_trpc/TRPCProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
            <Provider>
              <TRPCProvider>
              {children}
              </TRPCProvider>
            </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
